repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-toml
    - id: check-json
    - id: check-xml
    - id: check-added-large-files
      args: ['--maxkb=10240']  # 10 MB, picked from a hat
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: debug-statements
    - id: detect-private-key
    - id: forbid-new-submodules
    - id: mixed-line-ending
    - id: fix-encoding-pragma
    - id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782  # released 2020-06-24
    hooks:
    - id: mypy

-   repo: https://github.com/PyCQA/isort
    rev: 5.5.2  # Keep in sync with pyproject.toml
    hooks:
    -   id: isort
