[tool.poetry]
name = "mole-template"
version = "0.1.0"
description = "Do some things with to-do lists"
authors = ["Erich Blume <blume.erich@gmail.com>"]
license = "MIT License"
packages = [
    { "include" = "your_project", "from" = "src"},
]


[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.1"


[tool.poetry.dev-dependencies]
black = { version = "^21.7b0", allow-prereleases = true}
click = "^8.0.1"
flake8 = "^3.8.3"
flake8-isort = "^4.0.0"
isort = "5.9.2"  # Keep in sync with .pre-commit-config.yaml
mypy = "0.910"  # Keep in sync with .pre-commit-config.yaml
pdbpp = "^0.10.2"
pre-commit = "^2.7.1"
pytest = "^6.0.2"
pytest-cov = "^2.10.1"
pytest-flake8 = "^1.0.7"
pytest-lazy-fixture = "^0.6.3"
pytest-mypy = "^0.8.0"
pytest-sugar = "^0.9.4"
pytest-xdist = {version = "^2.1.0", extras = ["psutil"]}


[tool.pytest.ini_options]
addopts = "--strict-markers --color=yes --mypy --import-mode=importlib"
testpaths = ["tests"]
minversion = "6.0"
python_functions = ['test_*', 'example_*']
xfail_strict = true
# To add more warning filters, use this syntax:
# https://docs.python.org/3/library/warnings.html#describing-warning-filters
#     action:message:category:module:line
filterwarnings = [
    "error",  # MUST BE FIRST. Promotes all warnings to errors, unless filtered
]


[tool.black]
line-length = 100  # Keep isort, flake8, and black line length in sync


[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_single_line = false
lexicographical = true
order_by_type = false
force_sort_within_sections = true
line_length = 100 # Keep isort, flake8, and black line length in sync

[tool.mypy]
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true
mypy_path = "src"
files = [
    "src/**/*.py",
    "tests/**/*.py",
]

# How to ignore files with mypy
# EXAMPLE: Don't check for errors in migration files.
# [mypy-apps.*.migrations.*]
# ignore_errors = True


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
