[tool.poetry]
name = "mole"
version = "0.1.0"
description = "Do some things with to-do lists"
authors = ["Erich Blume <blume.erich@gmail.com>"]
license = "MIT License"
packages = [
    { "include" = "mole", "from" = "src"},
]


[tool.poetry.dependencies]
python = ">=3.9,<4.0"
tzlocal = ">=2.1"
requests = "^2.28.1"
typer = {extras = ["all"], version = "^0.6.1"}


[tool.poetry.scripts]
mole = 'mole.__main__'


[tool.poetry.group.dev.dependencies]
types-requests = "^2.28.8"  # Keep in sync with .pre-commit-config.yaml
black = { version = "22.6.0", allow-prereleases = true}
isort = "5.10.0"  # Keep in sync with .pre-commit-config.yaml
mypy = "0.971"  # Keep in sync with .pre-commit-config.yaml
pre-commit = "^2.20"
pytest = "^6.0"
pytest-cov = "^2.10"
pytest-lazy-fixture = "^0.6"
pytest-mypy = "^0.8"
pytest-sugar = "^0.9"
pytest-xdist = {version = "^2.1", extras = ["psutil"]}
pdbpp = "^0.10"


[tool.pytest.ini_options]
# addopts = "--strict-markers --color=yes --mypy --import-mode=importlib"
addopts = "--strict-markers --color=yes --mypy"
testpaths = ["tests"]
minversion = "6.0"
python_functions = ['test_*', 'example_*']
xfail_strict = true
# To add more warning filters, use this syntax:
# https://docs.python.org/3/library/warnings.html#describing-warning-filters
#     action:message:category:module:line
filterwarnings = [
    "error",  # MUST BE FIRST. Promotes all warnings to errors, unless filtered
]


[tool.black]
line-length = 100  # Keep isort and black line length in sync


[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_single_line = false
lexicographical = true
order_by_type = false
force_sort_within_sections = true
line_length = 100 # Keep isort and black line length in sync

[tool.mypy]
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/stubs"
files = [
    "src/**/*.py",
    "tests/**/*.py",
]

# How to ignore files with mypy
# EXAMPLE: Don't check for errors in migration files.
# [mypy-apps.*.migrations.*]
# ignore_errors = True


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
