[tool.poetry]
name = "mole"
version = "0.2.2"
description = "Do some things with to-do lists"
authors = ["Erich Blume <blume.erich@gmail.com>"]
license = "MIT License"
readme = "README.md"
packages = [
    { "include" = "mole", "from" = "src"},
]

[tool.poetry.dependencies]
python = "^3.11"
typer = {extras = ["all"], version = "^0.9"}
requests = "2.28.2"
requests-toolbelt = "^0.10.1"
todoist-api-python = "^2.0.2"
jira = "^3.5.0"
psutil = "^5.9.5"
openai = "^0.27.6"
python-dateutil = "^2.8.2"
boto3 = "^1.26.140"
ruff = "^0.0.278"
rich = "^13.4.2"
types-psutil = "^5.9.5.15"
types-python-dateutil = "^2.8.19.13"
plumbum = "^1.8.2"

[tool.poetry.scripts]
mole = 'mole.__main__:main'

[tool.poetry.group.dev.dependencies]
types-requests = "2.28.11.8"  # Keep in sync with .pre-commit-config.yaml
mypy = "^1.4.1"  # Keep in sync with .pre-commit-config.yaml
pre-commit = "^3.0"
pytest = "^7.2"
pytest-cov = "^4.0"
pytest-mypy = "^0.10"
pytest-sugar = "^0.9"
pdbpp = "^0.10"
pytest-mock = "^3.10"
ipython = "^8.12.0"
types-python-dateutil = "^2.8.19.13"

[tool.pytest.ini_options]
addopts = "--strict-markers --color=yes --mypy"
testpaths = ["tests"]
python_functions = ['test_*', 'example_*']
xfail_strict = true
# To add more warning filters, use this syntax:
# https://docs.python.org/3/library/warnings.html#describing-warning-filters
#     action:message:category:module:line
filterwarnings = [
    "error",  # MUST BE FIRST. Promotes all warnings to errors, unless filtered
]

[tool.mypy]
ignore_missing_imports = true
files = [
    "src/**/*.py",
    # "tests/**/*.py",
]

[tool.ruff]
fix = true
line-length = 120
ignore = [
    "E501",  # Line too long
]

# How to ignore files with mypy
# EXAMPLE: Don't check for errors in migration files.
# [mypy-apps.*.migrations.*]
# ignore_errors = True

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
