[tool.poetry]
name = "mole"
version = "0.4.15"
description = "Personal automation project"
authors = ["Erich Blume <blume.erich@gmail.com>"]
license = "MIT License"
readme = "README.md"
packages = [
    { "include" = "mole", "from" = "src"},
]

[tool.poetry.dependencies]
python = "^3.11"
typer = {extras = ["all"], version = "^0.9"}
todoist-api-python = "^2.1.3"
openai = "^1.2.4"
rich = "^13.4.2"
watchdog = "^3.0.0"
pendulum = "^2.1.2"
pydub = "^0.25.1"
requests = "^2.31.0"
pyyaml = "^6.0.1"
typerassistant = "^0.2.5"
pydantic = "^2.5.2"

[tool.poetry.scripts]
mole = 'mole.__main__:main'

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.0"
ruff = "^0.1.1"
ipdb = "^0.13.13"
pdbpp = "^0.10.3"

[tool.ruff]
line-length = 120
target-version = "py311"
# Default select = ["E4", "E7", "E9", "F"]
select = ["E4", "E7", "E9", "F", "W", "I"]

[tool.ruff.lint]
ignore = [
    "E501",  # line too long
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
