[tool.poetry]
name = "mole"
version = "0.3.0"
description = "Personal automation project"
authors = ["Erich Blume <blume.erich@gmail.com>"]
license = "MIT License"
readme = "README.md"
packages = [
    { "include" = "mole", "from" = "src"},
]

[tool.poetry.dependencies]
python = "^3.11"
typer = {extras = ["all"], version = "^0.9"}
todoist-api-python = "^2.1.3"
openai = "^0.27.6"
rich = "^13.4.2"
apache-airflow = "^2.7.2"
connexion = "<3"

[tool.poetry.scripts]
mole = 'mole.__main__:main'

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.0"
ruff = "^0.1.1"

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
ignore = [
    "E501",  # line too long
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
