from .generic import Manager as Manager
from typing import Any

class BizInvitationsManager(Manager):
    state_name: Any = ...
    object_type: Any = ...
    def accept(self, invitation_id: Any, invitation_secret: Any) -> None: ...
    def reject(self, invitation_id: Any, invitation_secret: Any) -> None: ...
