from .generic import Manager as Manager
from typing import Any

class BusinessUsersManager(Manager):
    def invite(self, email_list: Any): ...
    def accept_invitation(self, id: Any, secret: Any): ...
    def reject_invitation(self, id: Any, secret: Any): ...
