from .generic import Manager as Manager, SyncMixin as SyncMixin
from typing import Any

class CollaboratorStatesManager(Manager, SyncMixin):
    state_name: str = ...
    object_type: Any = ...
    def get_by_ids(self, project_id: Any, user_id: Any): ...
