from .generic import GetByIdMixin as GetByIdMixin, Manager as Manager, SyncMixin as SyncMixin
from typing import Any

class CollaboratorsManager(Manager, GetByIdMixin, SyncMixin):
    state_name: str = ...
    object_type: Any = ...
    def delete(self, project_id: Any, email: Any) -> None: ...
