from .. import models as models
from .generic import AllMixin as AllMixin, GetByIdMixin as GetByIdMixin, Manager as Manager, SyncMixin as SyncMixin
from typing import Any

class FiltersManager(Manager, AllMixin, GetByIdMixin, SyncMixin):
    state_name: str = ...
    object_type: str = ...
    def add(self, name: Any, query: Any, **kwargs: Any): ...
    def update(self, filter_id: Any, **kwargs: Any) -> None: ...
    def delete(self, filter_id: Any) -> None: ...
    def update_orders(self, id_order_mapping: Any) -> None: ...
    def get(self, filter_id: Any): ...
