from typing import Any, Optional

class Manager:
    state_name: Any = ...
    object_type: Any = ...
    api: Any = ...
    def __init__(self, api: Any) -> None: ...
    @property
    def state(self): ...
    @property
    def queue(self): ...
    @property
    def token(self): ...

class AllMixin:
    def all(self, filt: Optional[Any] = ...): ...

class GetByIdMixin:
    def get_by_id(self, obj_id: Any, only_local: bool = ...): ...

class SyncMixin:
    def sync(self): ...
