from .generic import Manager as Manager, SyncMixin as SyncMixin
from typing import Any

class InvitationsManager(Manager, SyncMixin):
    state_name: Any = ...
    object_type: str = ...
    def accept(self, invitation_id: Any, invitation_secret: Any) -> None: ...
    def reject(self, invitation_id: Any, invitation_secret: Any) -> None: ...
    def delete(self, invitation_id: Any) -> None: ...
