from .generic import AllMixin as AllMixin, GetByIdMixin as GetByIdMixin, Manager as Manager, SyncMixin as SyncMixin
from typing import Any

class LiveNotificationsManager(Manager, GetByIdMixin, AllMixin, SyncMixin):
    state_name: str = ...
    object_type: Any = ...
    def set_last_read(self, id: Any) -> None: ...
    def mark_read(self, id: Any) -> None: ...
    def mark_read_all(self) -> None: ...
    def mark_unread(self, id: Any) -> None: ...
