from .generic import AllMixin as AllMixin, Manager as Manager, SyncMixin as SyncMixin
from typing import Any

class LocationsManager(Manager, AllMixin, SyncMixin):
    state_name: str = ...
    object_type: Any = ...
    def clear(self) -> None: ...
