from .. import models as models
from .generic import AllMixin as AllMixin, GetByIdMixin as GetByIdMixin, Manager as Manager, SyncMixin as SyncMixin
from typing import Any

class GenericNotesManager(Manager, AllMixin, GetByIdMixin, SyncMixin):
    object_type: str = ...
    def update(self, note_id: Any, **kwargs: Any) -> None: ...
    def delete(self, note_id: Any) -> None: ...

class NotesManager(GenericNotesManager):
    state_name: str = ...
    def add(self, item_id: Any, content: Any, **kwargs: Any): ...
    def get(self, note_id: Any): ...

class ProjectNotesManager(GenericNotesManager):
    state_name: str = ...
    def add(self, project_id: Any, content: Any, **kwargs: Any): ...
    def get(self, note_id: Any): ...
