from .. import models as models
from .generic import AllMixin as AllMixin, GetByIdMixin as GetByIdMixin, Manager as Manager, SyncMixin as SyncMixin
from typing import Any

class ProjectsManager(Manager, AllMixin, GetByIdMixin, SyncMixin):
    state_name: str = ...
    object_type: str = ...
    def add(self, name: Any, **kwargs: Any): ...
    def update(self, project_id: Any, **kwargs: Any) -> None: ...
    def delete(self, project_id: Any) -> None: ...
    def archive(self, project_id: Any) -> None: ...
    def unarchive(self, project_id: Any) -> None: ...
    def move(self, project_id: Any, parent_id: Any) -> None: ...
    def reorder(self, projects: Any) -> None: ...
    def share(self, project_id: Any, email: Any) -> None: ...
    def get_archived(self): ...
    def get_data(self, project_id: Any): ...
    def get(self, project_id: Any): ...
