from .. import models as models
from .generic import AllMixin as AllMixin, GetByIdMixin as GetByIdMixin, Manager as Manager, SyncMixin as SyncMixin
from typing import Any

class RemindersManager(Manager, AllMixin, GetByIdMixin, SyncMixin):
    state_name: str = ...
    object_type: str = ...
    def add(self, item_id: Any, **kwargs: Any): ...
    def update(self, reminder_id: Any, **kwargs: Any) -> None: ...
    def delete(self, reminder_id: Any) -> None: ...
    def get(self, reminder_id: Any): ...
