from .. import models as models
from .generic import AllMixin as AllMixin, GetByIdMixin as GetByIdMixin, Manager as Manager, SyncMixin as SyncMixin
from typing import Any

class SectionsManager(Manager, AllMixin, GetByIdMixin, SyncMixin):
    state_name: str = ...
    object_type: str = ...
    def add(self, name: Any, project_id: Any, **kwargs: Any): ...
    def update(self, section_id: Any, **kwargs: Any) -> None: ...
    def delete(self, section_id: Any) -> None: ...
    def move(self, section_id: Any, project_id: Any) -> None: ...
    def archive(self, section_id: Any, **kwargs: Any) -> None: ...
    def unarchive(self, section_id: Any) -> None: ...
    def reorder(self, sections: Any) -> None: ...
    def get(self, section_id: Any): ...
