from .generic import Manager as Manager
from typing import Any

class TemplatesManager(Manager):
    def import_into_project(self, project_id: Any, filename: Any, **kwargs: Any): ...
    def export_as_file(self, project_id: Any, **kwargs: Any): ...
    def export_as_url(self, project_id: Any, **kwargs: Any): ...
