from .generic import Manager as Manager
from typing import Any

class UploadsManager(Manager):
    def add(self, filename: Any, **kwargs: Any): ...
    def get(self, **kwargs: Any): ...
    def delete(self, file_url: Any): ...
