from .generic import Manager as Manager
from typing import Any, Optional

class UserManager(Manager):
    def update(self, **kwargs: Any) -> None: ...
    def update_goals(self, **kwargs: Any) -> None: ...
    def sync(self): ...
    def get(self, key: Optional[Any] = ..., default: Optional[Any] = ...): ...
    def get_id(self): ...
    def login(self, email: Any, password: Any): ...
    def login_with_google(self, email: Any, oauth2_token: Any, **kwargs: Any): ...
    def register(self, email: Any, full_name: Any, password: Any, **kwargs: Any): ...
    def delete(self, current_password: Any, **kwargs: Any): ...
    def update_notification_setting(self, notification_type: Any, service: Any, dont_notify: Any): ...
