name: Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install the project
        run: uv sync --locked --all-extras

      - name: Check Version
        id: check-version
        run: |
          [[ "$(uv run mole version)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || echo prerelease=true >> $GITHUB_OUTPUT

      - name: Run unit tests
        id: test-build
        run: uv run pytest

      - name: Build dist artifacts
        id: build-dist
        run: uv build

      # (same note on source as check-version)
      - name: Create Release
        uses: ncipollo/release-action@v1.16.0  # Feb 22 2025
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: steps.check-version.outputs.prerelease == 'true'
